### ISSUE TITLE
[Bug]: Installer App always Crashes

### ISSUE THREAD

**Issue by lightyuwu** [LemonLoader/MelonLoader#10]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

The Installer always Crashes on the Splash Screen, so i can not use it.
I am using an Android ZTE Blade V10 Vita.
The Android/com.lavagang.melonloader.installer doesn't exist, probably because the app crashes before it can create it.

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by TrevTV** [comment]
Are you able to post the output of `adb logcat` when launching the installer?

**Comment by lightyuwu** [comment]
Here: 
[lemon-logcat-output.log](https://github.com/user-attachments/files/17240213/lemon-logcat-output.log)

**Comment by lightyuwu** [comment]
The App doesn't even work on my Tablet, and the PC .exe, while it does start, it is unable to find any apps, and the icons there are all corrupted.

**Comment by TrevTV** [comment]
That's odd, considering even the Windows installer doesn't work, your device must be fighting against the installer's query for what apps you have installed. Not sure if I can do much about that.

**Comment by lightyuwu** [comment]
The weird Thing is the old installer worked without failure...

**Comment by TrevTV** [comment]
I can't replicate this (nor have I seen others with this issue) so there isn't much I can do frankly

**Comment by lightyuwu** [comment]
That's sad.. If the old installer would still Work, I would use that. But i guess i'm just out of luck...

**Comment by lightyuwu** [comment]
Unless, of course there's source code for it available. Then i could debug it myself and hopefully figure it out, but i can't find it.

**Comment by lightyuwu** [comment]
Alright, I have a new Update. It works on  my Android 13 phone, but then i can't get past this when running a patched game: ![Screenshot_20241205_070331.jpg](https://github.com/user-attachments/assets/5e4904ef-fa18-4a39-9e46-c62bfc2c89a6)

Did i do something wrong or is it because of my 256GB Storage? (I doubt the latter)

**Comment by TrevTV** [comment]
I can't recall why this appears, if I had to guess, it's a permission issue.

**Comment by TrevTV** [comment]
Closing as the issue seems to be specific to the device and the new issue is unrelated.
