### ISSUE TITLE
[Bug]: "There was a problem parsing the package"

### ISSUE THREAD

**Issue by Kiffolisk** [LemonLoader/MelonLoader#13]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the game.
- [ ] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

This isn't exactly related to LemonLoader injection, but I can't install the installer APK on an Android 7 Samsung Galaxy Tab S2 with the error "There was a problem parsing the package."

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
I was only able to find some random 3rd party information, but it seems like the chipset that your device uses doesn't support ARM64 and Lemon currently only supports ARM64

**Comment by nullgrim** [comment]
> I was only able to find some random 3rd party information, but it seems like the chipset that your device uses doesn't support ARM64 and Lemon currently only supports ARM64

I am using bluestacks, it's running ARM64 and I have the same issue.

**Comment by TrevTV** [comment]
> I am using bluestacks, it's running ARM64 and I have the same issue.
Bluestacks is funky and is unsupported for any standard Lemon releases.

No other information has been given so I am closing this, feel free to reopen if needed
