### ISSUE TITLE
[Bug]: folder not working

### ISSUE THREAD

**Issue by Fupeodid** [LemonLoader/MelonLoader#13]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [x] Tried reinstalling the app.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting the device.

### Describe the issue.

When I use lemonloader on my phone and patch a apk the melonloader folder shows up in /storage/emulated/0/melonloader but on my vr when I use it, the folder dosent show up.

### Did you attach your log file?

No, I could not find a log file

**Comment by TrevTV** [comment]
You have to run the patched game before the folder is made.

**Comment by Fupeodid** [comment]
> You have to run the patched game before the folder is made.

But I did I patched it, then I ran it and it still wasent made
