### ISSUE TITLE
[Bug]: Doesn't work with Super Bear Adventure

### ISSUE THREAD

**Issue by Segually** [LemonLoader/MelonLoader#14]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the app.
- [X] Tried reinstalling LemonLoader.
- [x] Tried restarting the device.

### Describe the issue.

I tried to patch the game Super Bear Adventure. The patch worked, but when I sideload it onto my Huawei MediaPad AGS-W09, it says "App not installed."

I made the patch on my computer since the APK wasn't compatible with my tablet, which runs Android 8.

I used the "Continue without a device" option to load the game APK. It patched successfully, but it didn’t install. When I tried the "Continue with a device" option, it didn’t work because the device didn’t show up in LemonLoader, even after I reopened the EXE.

[24-10-9_18-11-3.log](https://github.com/user-attachments/files/17311963/24-10-9_18-11-3.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by TrevTV** [comment]
I can't replicate this, my assumption is that your tablet's Android version is too old to support Lemon, and I have no intention on supporting older versions of Android.
