### ISSUE TITLE
[Bug]: Failed to parse Unity version

### ISSUE THREAD

**Issue by DeleteRune** [LemonLoader/MelonLoader#15]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the app.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting the device.

### Describe the issue.

I tried install from Windows (I couldn't run app on device). Presumably, Unity version is 2021.3.28f1.

[24-10-9_19-29-8.log](https://github.com/user-attachments/files/17314035/24-10-9_19-29-8.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by TrevTV** [comment]
What app is this happening on?

**Comment by Pietrodjaowjao** [comment]
Change the order so app name and package is always logged first too lol

**Comment by DeleteRune** [comment]
Sorry for the long wait for a response.

> What app is this happening on?

Limbus Company. I have a theory that detecting the Unity version might be blocked at the software level by AppSealing. However, when I tried to patch an older version of the APK, everything worked successfully (that version also had AppSealing).

> Change the order so app name and package is always logged first too lol

Could you explain this method in more detail? I didn't quite understand how to do it, to be honest. Also, I think your explanation could help others in the future if they encounter the same problem.

**Comment by TrevTV** [comment]
They were directing that towards me I assume, not you.

Looks like the game separates it's assets into a different APK than where the installer is searching for them. I should be able to make a fix, though not sure when I'll get around to it.

**Comment by TrevTV** [comment]
Fixed, will be available with the next release, whenever that will be.
