### ISSUE TITLE
Chinese Unity versions are unstripped incorrectly

### ISSUE THREAD

**Issue by AthallahDzaki** [LemonLoader/MelonLoader#17]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the app.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting the device.

### Describe the issue.

I tried to patch PVZRH, But the following error appears when I start the ga
![The Error](https://github.com/user-attachments/assets/53049dbb-83fe-4d56-b910-615e981a871f)
me.
[Latest.log](https://github.com/user-attachments/files/17350847/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by TrevTV** [comment]
The error is due to the native libraries used to unstrip games being for international Unity while that game uses Chinese Unity, this will likely take awhile to fix properly.

After working around the issue, the game also suffers from #8 which causes it to crash regardless.

**Comment by TrevTV** [comment]
Chinese Unity unstripping is fixed, will be part of the next release.
Game still does not work due to #8, however.
