### ISSUE TITLE
[Bug]: SceneManager.sceneLoaded override failed, and throw Sequence contains more than one matching element exception

### ISSUE THREAD

**Issue by lxymahatma** [LemonLoader/MelonLoader#18]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the app.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting the device.

### Describe the issue.

[Latest.log](https://github.com/user-attachments/files/17381440/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by TrevTV** [comment]
This is a known issue with Muse Dash, it's fixed in the source but not the release, now it leads to the same issue in #8 which I have yet to fix.
