### ISSUE TITLE
[Enhancement]: Old Versions

### ISSUE THREAD

**Issue by MrmysteryV** [LemonLoader/MelonLoader#19]
### Describe the new feature or enhancement

Hello, could the old versions of this be added back to the github (ideally 0.1.1) so that the installers for those versions still work for things like patch 3 bonelab fusion. If this is not the reason of the problem, then my apologies. If this cannot be done, could I be informed on how to compile a custom version with a repository change in the source code to make it function again. Thank you lots

**Comment by TrevTV** [comment]
[LemonLoader/MelonLoader_057](https://github.com/LemonLoader/MelonLoader_057/releases/tag/0.2.0.1)
