### ISSUE TITLE
[Enhancement]: Return CopyToData

### ISSUE THREAD

**Issue by dimbox-idk** [LemonLoader/MelonLoader#22]
### Describe the new feature or enhancement

Can you add back copyToData or something like it? This was very helpful.

**Comment by dimbox-idk** [comment]
I don’t know if it exists because there is no information about it on Wiki.

**Comment by TrevTV** [comment]
On my list of things to do (frankly I had no idea anyone actually used it other than me)
No clue when I'll get around to it

**Comment by dimbox-idk** [comment]
Thanks!
[Click](https://github.com/LemonLoader/MelonLoader/commit/785e72707d1c0c002fa848ce9284520af85f2267)
