### ISSUE TITLE
[Bug]: The application doesn't install BoneLab back for an unspecified reason

### ISSUE THREAD

**Issue by thebashforkbomber** [LemonLoader/MelonLoader#24]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the app.
- [ ] Tried reinstalling LemonLoader.
- [ ] Tried restarting the device.

### Describe the issue.

The log was overwritten.
What I've done:
I've allowed all of the required permissions
I patched strictly the original app.
I tried installing the app 4 times, yet every single one has failed.

### Did you attach your log file?

No, I could not find a log file

**Comment by TrevTV** [comment]
Haven't been able to replicate, nor have seen anyone else with the issue, my guess is your device just dislikes how the installer works.
