### ISSUE TITLE
[Bug]: BoneLab inf loading

### ISSUE THREAD

**Issue by MochaDEBUG** [LemonLoader/MelonLoader#29]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the app.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting the device.

### Describe the issue.

When trying to follow a tutorial to get code mods on bonelab and i got stuck on an inf three dot loading screen and I have not found a way to fix it and I think its something to do with the obb files of bonelab and when i checked the file it had two thingys one started with "main" and the other started with "patch"
![Screenshot 2024-11-29 172722](https://github.com/user-attachments/assets/e367b6df-8a50-4705-90ef-3a91c02f8121)

### Did you attach your log file?

No, I could not find a log file

**Comment by TrevTV** [comment]
Unable to replicate, make sure you granted the file permission when the game launched, sometimes it is hidden and you have to press the Oculus button to show it. If that doesn't work, just try restarting the game as it's possible it just got stuck somewhere. If neither fix it, uninstall the game, restart your headset, reinstall it, and try again.

**Comment by TrevTV** [comment]
No response from issue author, closing.

**Comment by RatKing528** [comment]
I'm having the same issue (this is standalone quest obviously) I tried restarting my headset, I uninstalled melon loader and reinstalled, I uninstalled bonelab, I even did a combo of all three. But it didn't work I allowed all the stuff but for some reason it just inf loads
