### ISSUE TITLE
[Bug]: Patching fails with latest version of MelonLoader trying to patch latest version of BTD66

### ISSUE THREAD

**Issue by blankuserrr** [LemonLoader/MelonLoader#30]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the app.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting the device.

### Describe the issue.

Title pretty much sums it up, melonloader fails to patch Bloons Tower Defense 6. There's a 404 when fetching unity deps as shown in the log, which is most likely why it's failing.
[24-12-12_8-4-43.log](https://github.com/user-attachments/files/18112017/24-12-12_8-4-43.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by blankuserrr** [comment]
This seems to be an issue with `Dependencies/Il2CppAssemblyGenerator/Packages/UnityDependencies.cs`, among other parts. The log states it's looking for `2022.3.49f1`, but [MelonLoader's libraries](https://github.com/LavaGang/Unity-Runtime-Libraries) only has `2022.3.49`

**Comment by TrevTV** [comment]
The needed libraries were added. I still would not expect the game to run due to #8, though I haven't actually tested BTD6.

**Comment by blankuserrr** [comment]
Thanks, it patches successfully now. But you're right, it doesn't run.
