### ISSUE TITLE
[Bug]: Audica fails to launch after ~30 seconds

### ISSUE THREAD

**Issue by SoffiMeower** [LemonLoader/MelonLoader#31]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the app.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting the device.

### Describe the issue.

[Latest.log](https://github.com/user-attachments/files/18138145/Latest.log)
After Audica prompts the user for file access, it'll stay on the Quest loading screen for 30sec-1min before exiting.

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by TrevTV** [comment]
Can you re-post the log? GitHub is just throwing an error when opening it

**Comment by TrevTV** [comment]
Ran the game myself, looks like Audica suffers from #8 and https://github.com/BepInEx/Il2CppInterop/issues/187, neither are fixed currently.

**Comment by SoffiMeower** [comment]
> Can you re-post the log? GitHub is just throwing an error when opening it

Github tweaking as usual XD
