### ISSUE TITLE
[Bug]: Diversion black screen

### ISSUE THREAD

**Issue by Kiffolisk** [LemonLoader/MelonLoader#7]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

I'm trying to get Diversion to work with LemonLoader, but I just get a black screen no matter how long I wait.
[Latest.log](https://github.com/LemonLoader/MelonLoader/files/10348314/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Log is saying Lemon was able to initialize perfectly fine, I'll have to do some more digging when I have the time.

**Comment by Kiffolisk** [comment]
yeah i noticed that, its just a black screen. i restarted my phone again and it just crashes

**Comment by TrevTV** [comment]
Seems to be an issue with libunity.so stripping, I'm pretty much clueless on that part of Android modding so I wouldn't expect much right now. I'm going to close this but move the issue to #8 so it isn't Diversion specific
