### ISSUE TITLE
Latest version is not compatible with the quest version "V63": 

### ISSUE THREAD

**Issue by Evelyn-dumbass** [LemonLoader/MelonLoader#79]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

I recently factory reset my headset because I have been getting bad performance on many games, but after I factory reset my quest updated to version 63 and I tried using lemon loader but a "error" of sorts comes up whenever I try giving it permissions "Cant use this folder. To protect your privacy, choose another folder". I would appreciate if this can be fixed so I can start having fun modding games again. Thanks for reading!

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by maxhax123** [comment]
yeah, they need to make it ask for manage all files THEN data and it should work

**Comment by maxhax123** [comment]
or just release it to applab

**Comment by Evelyn-dumbass** [comment]
> yeah, they need to make it ask for manage all files THEN data and it should work

It does, its a problem to do with the android version its using. Its nothing to do with LemonLoader, but I made this issue to make sure they know about this issue and see if they can fix it. Also switching it to applab it will still have the same problem.

**Comment by TrevTV** [comment]
Wait for Meta to fix it, or wait for me to maybe possibly do #81
