### ISSUE TITLE
[Bug]:  Quest 3 lemon loader patch made bonelab become unuseable

### ISSUE THREAD

**Issue by inf-solutions** [LemonLoader/MelonLoader#88]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [ ] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Everytime after patching i press yes uninstall install then i launch the game... dark grey screen for over 10 minutes will not launch anymore please help...

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Probably didn't save the game's OBBs which are required for loading. Lemon does not save them automatically.
